- name: Copy runtime.properties for Druid overlord
  template: src=runtime.properties dest=/usr/local/druid/conf/druid/overlord/
        owner={{ ansible_user }} mode=0755
  become: yes

- name: Copy jvm.config for Druid overlord
  template: src=jvm.config dest=/usr/local/druid/conf/druid/overlord/
        owner={{ ansible_user }} mode=0755
  become: yes
